### ISSUE TITLE
pdksh never checks process status after rfork.

### ISSUE THREAD

**Issue by rminnich** [Harvey-OS/apex#68]
ratrace shows pdksh returning from rfork. There are no more system calls after that -- it's stuck.

it would be nice to know why it never tries to get process exit status.

**Comment by elbing** [comment]
#69 adds panic function, now remaining patches for pdksh and mksh or implementation of sigsuspend.

**Comment by elbing** [comment]
See #70

**Comment by elbing** [comment]
Harvey #582 solved signaling problem and #70
