### ISSUE TITLE
Signals are not working

### ISSUE THREAD

**Issue by elbing** [Harvey-OS/apex#71]
Steps for reproducing it:
Cloning APEX.
```
git clone https://github.com/Harvey-OS/apex.git
```

Merging last PR WIP:
```
git checkout -b elbing-sigsuspend master
git pull https://github.com/elbing/apex.git sigsuspend
```

Building APEX:
```
ARCH=amd64 HARVEY=<PATH-TO-HARVEY-LOCAL-TREE> APEX=$(pwd) OS=linux make
```
Be sure you have built Harvey with gcc and APEX is built with gcc, with clang there could be rare issues. 

(For me, harvey clang 4.0 + apex clang 4.0 with cmds and testcase with clang 4.0 in ubuntu are working...)

Building a test case:

testkill.c (ok, look for any other better):

```c
#include <stdio.h>
#include <stdlib.h>
#include <sys/types.h>
#include <signal.h>
#include <unistd.h>

/* When a SIGUSR1 signal arrives, set this variable. */
volatile sig_atomic_t usr_interrupt = 0;

void
synch_signal (int sig)
{
  usr_interrupt = 1;
}

/* The child process executes this function. */
void
child_function (void)
{
  /* Perform initialization. */
  printf ("I'm here!!!  My pid is %d.\n", (int) getpid ());

  /* Let parent know you’re done. */
  kill (getppid (), SIGUSR1);

  /* Continue with execution. */
  puts ("Bye, now....");
  exit (0);
}

int
main (void)
{
  struct sigaction usr_action;
  sigset_t block_mask;
  pid_t child_id;

  /* Establish the signal handler. */
  sigfillset (&block_mask);
  usr_action.sa_handler = synch_signal;
  usr_action.sa_mask = block_mask;
  usr_action.sa_flags = 0;
  sigaction (SIGUSR1, &usr_action, NULL);

  /* Create the child process. */
  child_id = fork ();
  if (child_id == 0)
    child_function ();          /* Does not return. */

  /* Busy wait for the child to send a signal. */
  while (!usr_interrupt)
    ;

  /* Now continue execution. */
  puts ("That's all, folks!");

  return 0;
}
```
building the test case:
```
gcc -std=c11 -O2 -static -mno-red-zone -ffreestanding -nostdinc -nostdlib -D_SUSV2_SOURCE -D_POSIX_SOURCE -D_LIMITS_EXTENSION -D_BSD_EXTENSION -D_BSD_SOURCE -DHARVEY -Wall -Wuninitialized -g -I<PATH-YOUR-APEX-TREE>/harvey/apex/include -I<PATH-YOUR-APEX-TREE>/apex/amd64/include -c testkill.c; ld -static -nostdlib -o testkill <PATH-YOUR-APEX-TREE>/apex/amd64/lib/crt1.o <PATH-YOUR-APEX-TREE>/apex/amd64/lib/crti.o <PATH-YOUR-APEX-TREE>/apex/amd64/lib/crtn.o testkill.o -L<PATH-YOUR-APEX-TREE>/apex/amd64/lib -L<PATH-YOUR-HARVEY-TREE>/harvey/amd64/lib -lap -lc
```
Replace *<PATH-TO-YOUR...>* for your local set up.

Place the binary into the harvey tree you're using with ufs/ninep and see how it suicides due to write fault in notecont() (lib/ap/notetramp.c)

program execution under linux:

```
I'm here!!!  My pid is 21754.
Bye, now....
That's all, folks!
```

**Comment by gmacd** [comment]
Here's the commands I needed, assuming $HARVEY is set and apex is in $HARVEY/apex:
```gcc -std=c11 -O2 -static -mno-red-zone -ffreestanding -nostdinc -nostdlib -D_SUSV2_SOURCE -D_POSIX_SOURCE -D_LIMITS_EXTENSION -D_BSD_EXTENSION -D_BSD_SOURCE -DHARVEY -Wall -Wuninitialized -g -I$HARVEY/apex/include -I$HARVEY/apex/amd64/include -c testkill.c

ld -static -nostdlib -o testkill $HARVEY/apex/amd64/lib/crt1.o $HARVEY/apex/amd64/lib/crti.o $HARVEY/apex/amd64/lib/crtn.o testkill.o -L$HARVEY/apex/amd64/lib -L$HARVEY/amd64/lib -lap -lc```

**Comment by elbing** [comment]
Did you try running the program and seeing how it suicides at notetramp.c:44?
Gdb remote target doesn't admit reverse steps and we cannot run the program from gdb, so setting breakpoints are a bit useless here.
Nothandler is called as notify() argument in _envsetup.c which sets a posix env variable in stack for every program as a third arg in a hypothetic ansi main(argc, argv, env) function through crt1.s. It's the way (also other things) for storing in stack the signal handler. Translation from posix signals to harvey notify() message system is made through signal.c and notetramp.c (lib/ap/plan9 amd amd64).

Could someone try the test program in a plan9 ape? Original white paper is not so very clear about and I'm not sure if signals were working ok at all in old ape.

**Comment by gmacd** [comment]
Being able to launch the program from gdb would be useful here....

What I did was put a sleep(100); just before the call to fork().  I then attached gdb before fork() was called (since gdb stops the process on connection now, it stopped after the sleep).  It then received a SIGTRAP while waiting for the usr_interrupt.

**Comment by gmacd** [comment]
You could try connecting the debugger to the kernel via port 1234, and putting a breakpoint in port/fault.c:fault.

It could be another segment permissioning issue - I'm seeing the message:
```write fault fail, no segment, pid 96 addr 0xa6 pc 0x40369b```

**Comment by rminnich** [comment]
this is not a permissioning issue, note that the addr is a6, on page zero. When it's a number like a6 it usually means you had a null struct pointer and you offset from zero. My bet is a null pointer to some sort of struct.

**Comment by elbing** [comment]
Mmmm p->restorepc? (notetramp.c:44)

**Comment by elbing** [comment]
Harvey #583 solved this.
